import { ThemeProvider } from "@/components";
import "@/css/globals.css";

import { Suspense, type ReactNode } from "react";
import type { Metadata } from "next";
import type { IRSC } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<IRSC>): ReactNode {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<>loading...</>}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
